#!/bin/bash
set -e
MVN_COMMAND=${MVN_COMMAND:-"mvn"}
cd ${PULSAR_DIR}/tests/integration
TEST=${TEST:-"TestFileSystemOffload"}
PULSAR_TEST_IMAGE_NAME="apachepulsar/pulsar-test-latest-version:latest-tweak" $MVN_COMMAND test -Dtest=${TEST} -PintegrationTests -DredirectTestOutputToFile=false



