#!/bin/bash
set -e
MVN_COMMAND=${MVN_COMMAND:-"mvn"}
if [[ -z "$PULSAR_DIR" ]]; then
    echo "PULSAR_DIR not set"
    exit 1
fi
SKIP_PULSAR_BUILD=${SKIP_PULSAR_BUILD:-"false"}

HERE=$(pwd)

if [[ "$SKIP_PULSAR_BUILD" == "false" ]]; then
    cd ${PULSAR_DIR}
    ${MVN_COMMAND} clean install -Dspotbugs.skip -Dcheckstyle.skip -Dlicense.skip -Djavadoc.skip -DskipTests -am -pl docker/pulsar,docker/pulsar-all -Pdocker
    cd ${HERE}
fi

LATEST_VERSION_IMAGE_ROOT=${PULSAR_DIR}/tests/docker-images/latest-version-image
DOCKERFILE_PATH=${LATEST_VERSION_IMAGE_ROOT}/Dockerfile
rm -rf $DOCKERFILE_PATH
cp latest-docker-image-Dockerfile $DOCKERFILE_PATH

cd ${PULSAR_DIR}/tests/docker-images
${MVN_COMMAND} clean install -Dspotbugs.skip -Dcheckstyle.skip -Dlicense.skip -Djavadoc.skip  -DskipTests -Pdocker,-main -pl java-test-functions,latest-version-image
