#!/bin/bash
set -e
LATEST_VERSION_IMAGE_ROOT=${PULSAR_DIR}/tests/docker-images/latest-version-image
DOCKERFILE_PATH=${LATEST_VERSION_IMAGE_ROOT}/Dockerfile
rm -rf $DOCKERFILE_PATH
cp latest-docker-image-Dockerfile $DOCKERFILE_PATH

cd ${PULSAR_DIR}/tests/docker-images

mvnd clean install -DskipTests -Pdocker -pl java-test-functions,latest-version-image
